In [ ]:
#1 print first n natural num
for i in range(0,35,3):
  print(i)

0
3
6
9
12
15
18
21
24
27
30
33

In [ ]:
n=int(input('enter number:'))
for i in range(0,n):
  print(i)

In [ ]:
# Program to print even number using step size in range()
n = int(input("Enter the number "))  
for i in range(2,n,2):  
    print(i)

In [ ]:
#to print sum of first n natural num
sum=0
for i in range(0,8):
    sum=sum+i#0=0+0---0
    #0=0+1-----1
    #1=1+2---3
    #3=3+3
    #3=6+4--10
    #7=10+5--15
    #12=15+6-----21
    #18=21+7----28

print(sum)

28

In [ ]:
num=int(input("Enter number:"))
for j in range(1,11):
     print(num,'x', j,'=', num*j)

Enter number:5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

In [ ]:
num=int(input("enter the number"))
for i in range(1,11):
  print(num, 'x', i, '=', num*i)

enter the number1
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10

In [ ]:
num=int(input("enter the number"))
for i in range(1,11):
  print(num, 'x', i, '=', num*i)

In [ ]:
#3 find area of a circle
from math import pi#module contains functions to perform math oper
r = float(input ("radius of the circle : "))
area=pi*r*r
print ("The area of the circle with radius",area)

radius of the circle : 3
The area of the circle with radius 28.274333882308138

In [ ]:
#4
from math import *
print(sqrt(49))
print(pow(2,3))
print(factorial(5))
print(floor(4.4))#rounds to lower
print((ceil(4.5)))#rounds to upper

7.0
8.0
120
4
5

In [ ]:
plspls #5 input a number and check whether it is positive,neg or 0
n=int(input("enter the number"))
if(n==0):
  print("zero")
elif(n>0):
  print("positive")  
else:
  print("negative")

enter the number6
positive

In [ ]:
#6 print mul table of a number
num=int(input("enter the number"))
for i in range(1,11):
  print(num, 'x', i, '=', num*i)

enter the number3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

In [ ]:
n=int(input())
print(n)
for i in range(1,11):
  print(n,'x',i,'=',n*i)

In [ ]:
#7 write a function to find sum of all numbers in a list
def sum_list(items):
    sum_numbers = 0
    for x in items:
        sum_numbers=sum_numbers+x #increment by 1--> +=
    return sum_numbers
print(sum_list([2,3,0]))

5

In [ ]:
#8 write a program to find largest num of a list using function
def max_num_in_list( list ):
    max = list[ 0 ]
    for a in list:
        if a > max:
            max = a   #1,2
    
    return max
print(max_num_in_list([1, 2, -8, 0]))

2

In [ ]:
 # 9 find the list of words that are longer than n from a given string using function
def test_string(n, str):
    longer_words = []
    test_split = str.split(" ") 
    print(test_split) 
    for x in test_split:
        if len(x) > n:
            longer_words.append(x)
    return longer_words
test_string(3, "hello i am a girl")

['hello', 'i', 'am', 'a', 'girl']

['hello', 'girl']

In [ ]:
#10 convert a list to string
s = ['a', 'b', 'c', 'd']
string = ''.join(s)
print(string)

abcd

In [ ]:
s="abcd is a thing"
l=s.split()
print(l)

In [ ]:
#11 find unique values in a list
my_list = [10, 20, 30, 40, 20, 50, 60, 40]
print("Original List : ",my_list)
t = set(my_list)
my_new_list = list(t)
print("List of unique numbers : ",my_new_list)

Original List :  [10, 20, 30, 40, 20, 50, 60, 40]
List of unique numbers :  [40, 10, 50, 20, 60, 30]

In [ ]:
#12 Add a key value pair in existing dictionary
d = {0:10, 1:20}
print(d)
d.update({2:30})
print(d)

{0: 10, 1: 20}
{0: 10, 1: 20, 2: 30}

In [ ]:
#13 check if a key is already present
d = {'book':10, 'pen': 20, 3: 30, 4: 40, 5: 50, 6: 60}
def is_key_present(x):
  if x in d:
      print('Key is present in the dictionary')
  else:
      print('Key is not present in the dictionary')
is_key_present('ok')
is_key_present('book')

Key is not present in the dictionary
Key is present in the dictionary

In [ ]:
def add(x,y):
  return x+y
def multiplication(x,y):
  return x*y
def divi (x,y):
  return x-y
print("select operation")
print("1. Add ")
print("2. multiplication")
print("3. Subtraction")
choose=int(input("enter choice 1/2/3:"))
if choose==1
  
  #num1 = float (input("enter first number"))
  #num2 =float (input("enter second number"))

In [ ]:
#14 find sum of values
my_dict = {'data1':2,'data2':-5,'data3':247}
print(sum(my_dict.values()))

In [ ]:
#15concatenate 3 dictionaries and get a new one
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4 = {}
for d in (dic1, dic2, dic3): 
  dic4.update(d)
print(dic4)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

In [ ]:
 
#Assignment 1
#1.write a simple calulator program using function
#2. write a program to find smallest num in a list 
#3.Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included).
#4.Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.
#5. Write a Python program to print the even numbers from a given list using function
#6.print a dictionary where the keys are numbers between 1 and 15 (both included) and the values are square of keys
#7.find factorial of a number

In [ ]:
# 16 looping
statesAndCapitals = { 
                     'Gujarat' : 'Gandhinagar', 
                     'Maharashtra' : 'Mumbai', 
                     'Rajasthan' : 'Jaipur', 
                     'Bihar' : 'Patna'
                    } 
                      
print('List Of given states:\n') 
 
  
# Iterating over keys 
for state in statesAndCapitals: 
    print(state) 
print('capitals:\n')
# Iterating over values 
for capital in statesAndCapitals.values(): 
    print(capital) 
#print both   
print('\n') 
for state, capital in statesAndCapitals.items(): 
    print(state, ":", capital) 
for state in statesAndCapitals: 
    print(statesAndCapitals[state])

List Of given states:

Gujarat
Maharashtra
Rajasthan
Bihar
capitals:

Gandhinagar
Mumbai
Jaipur
Patna


Gujarat : Gandhinagar
Maharashtra : Mumbai
Rajasthan : Jaipur
Bihar : Patna
Gandhinagar
Mumbai
Jaipur
Patna

In [ ]:
number = 0

for number in range(10):
    if number == 5:
        break    # break here

    print('Number is ' + str(number))

print('Out of loop')

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Out of loop

In [ ]:
number = 0

for number in range(10):
    if number == 5:
        continue    # continue here
    if number==7:
      continue    

    print('Number is ' + str(number))

print('Out of loop')

Number is 0
Number is 1
Number is 2
Number is 3
Number is 4
Number is 6
Number is 8
Number is 9
Out of loop

In [ ]:
number = 0

for number in range(10):
    if number == 5:
        pass    # pass here

    #print('Number is ' + str(number))

print('Out of loop')

Out of loop

In [ ]:
3.#divisible by 7 and multiple of 5, between 1500 and 2700
mylist = []
for i in range(1500,2701):
	if ((i%7==0) and (i%5==0)):
		mylist.append(i)
print (mylist)

In [ ]:
number = 0

for number in range(10):
    if number == 5:
        pass    # pass here

    #print('Number is ' + str(number))

print('Out of loop')

In [ ]:
#4
#Python program that prints all the numbers from 0 to 6 except 3 and 6
#num = [0,1,2,3,4,5,6]
 
for i in range(6):
  if (i==3):
    continue
  print (i, end = ' ')
print ("\n")

0 1 2 4 5

In [ ]:
#even num
#Even numbers in a list
num1 = [0,1,2,3,4,5,6]
for i in num1:
  if i%2 == 0:
    print(i)

0
2
4
6

In [ ]:
def add(x,y):
  return x+y
def mul (x,y):
  return (x*y)
def subt(x,y):
  return (x-y)
print("select your operation")
print("1. Addition")
print("2. Multiplication")
print("3. Subtraction")
 
while True:
  Choice=int (input("select your number:"))
  if Choice in ('1','2','3'):
  num1=float (input("Enter first number:"))
  num2=float (input("Enter second number:"))
  if Choice =='1':
    print(num1, "+" ,num2,add(num1,num2))
  elif Choice =='2':
    print(num1,"x",num2,mul(num1,num2))
  elif Choice =='3':
    print(num1,"-",num2,subt(num1,num2))
break
#else :
 #print("invalid number")

In [ ]:
num=[0,1,2,3,4,5,6]
for i in num:
  if i%2!=0:
    print(i)

In [ ]:
#6#Print a dictionary
from math import *
d = dict()
for i in range (1,16):
   d[i] = pow(i,2)
print (d)

{1: 1.0, 2: 4.0, 3: 9.0, 4: 16.0, 5: 25.0, 6: 36.0, 7: 49.0, 8: 64.0, 9: 81.0, 10: 100.0, 11: 121.0, 12: 144.0, 13: 169.0, 14: 196.0, 15: 225.0}

In [ ]:
def factorial(num):
    if num == 1:
        return num
    else:
        return num * factorial(num - 1)
 
# User input 
num = int(input("Enter a Number: "))
 
# if input number is negative then return an error message
# elif the input number is 0 then display 1 as output
# else calculate the factorial by calling the user defined function
if num < 0:
    print("Factorial cannot be found for negative numbers")
elif num == 0:
    print("Factorial of 0 is 1")
else:
    print("Factorial of", num, "is: ", factorial(num))

In [ ]:
#print num from -10 to 1
for num in range(-10, 0, 1):
    print(num)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1